/**
 * Firebase Auto-Configuration Utilities
 *
 * Automatically configures Firebase by fetching config from Firebase CLI
 * and creating .env.local file during project generation
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import { writeFile } from './file-system.js';
import { logger } from './logger.js';
import path from 'path';

const execAsync = promisify(exec);

/**
 * Check if Firebase CLI is installed
 */
async function isFirebaseCLIInstalled(): Promise<boolean> {
  try {
    await execAsync('firebase --version');
    return true;
  } catch {
    return false;
  }
}

/**
 * Check if user is authenticated with Firebase
 */
async function isFirebaseAuthenticated(): Promise<boolean> {
  try {
    await execAsync('firebase projects:list');
    return true;
  } catch {
    return false;
  }
}

/**
 * Get current Firebase project
 */
async function getCurrentFirebaseProject(): Promise<string | null> {
  try {
    const { stdout } = await execAsync('firebase use');
    const match = stdout.match(/Active Project:\s+(\S+)/);
    return match && match[1] ? match[1] : null;
  } catch {
    return null;
  }
}

/**
 * Get Firebase web app config
 */
async function getFirebaseConfig(projectId: string): Promise<Record<string, string> | null> {
  try {
    // Get web apps list
    const { stdout: appsOutput } = await execAsync(`firebase apps:list WEB --project ${projectId}`);

    // Parse app ID from output
    const appMatch = appsOutput.match(/│\s+(\S+)\s+│/);
    if (!appMatch || !appMatch[1]) {
      logger.warning('No web app found in Firebase project');
      logger.info('You can create one later with: firebase apps:create WEB');
      return null;
    }

    const appId = appMatch[1];
    logger.info(`Found Firebase web app: ${appId}`);

    // Get app config
    const { stdout: configOutput } = await execAsync(
      `firebase apps:sdkconfig WEB ${appId} --project ${projectId}`
    );

    // Parse Firebase config from output
    const configMatch = configOutput.match(/const firebaseConfig = ({[\s\S]*?});/);
    if (!configMatch || !configMatch[1]) {
      logger.warning('Could not parse Firebase config');
      return null;
    }

    // Extract config values
    const configStr = configMatch[1];
    const config: Record<string, string> = {};

    const parseValue = (key: string): string => {
      const regex = new RegExp(`${key}:\\s*["']([^"']+)["']`);
      const match = configStr.match(regex);
      return match && match[1] ? match[1] : '';
    };

    config.apiKey = parseValue('apiKey');
    config.authDomain = parseValue('authDomain');
    config.projectId = parseValue('projectId');
    config.storageBucket = parseValue('storageBucket');
    config.messagingSenderId = parseValue('messagingSenderId');
    config.appId = parseValue('appId');
    config.measurementId = parseValue('measurementId');

    return config;
  } catch (error) {
    logger.warning('Failed to fetch Firebase config');
    if (error instanceof Error) {
      logger.info(`Error: ${error.message}`);
    }
    return null;
  }
}

/**
 * Create .env.local file with Firebase configuration
 */
async function createEnvFile(projectDir: string, config: Record<string, string>): Promise<boolean> {
  const envContent = `# Firebase Configuration
# Auto-generated by app-workspace-generator
# DO NOT commit this file to version control!

NEXT_PUBLIC_FIREBASE_API_KEY=${config.apiKey}
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${config.authDomain}
NEXT_PUBLIC_FIREBASE_PROJECT_ID=${config.projectId}
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${config.storageBucket}
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${config.messagingSenderId}
NEXT_PUBLIC_FIREBASE_APP_ID=${config.appId}
${config.measurementId ? `NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${config.measurementId}` : ''}
`;

  try {
    const envPath = path.join(projectDir, '.env.local');
    await writeFile(envPath, `${envContent.trim()}\n`);
    return true;
  } catch (_error) {
    logger.warning('Failed to create .env.local');
    return false;
  }
}

/**
 * Auto-configure Firebase during project generation
 */
export async function autoConfigureFirebase(projectDir: string): Promise<void> {
  logger.section('Firebase Auto-Configuration');

  // Check if Firebase CLI is installed
  const hasFirebaseCLI = await isFirebaseCLIInstalled();
  if (!hasFirebaseCLI) {
    logger.warning('Firebase CLI not found');
    logger.info('Install it with: npm install -g firebase-tools');
    logger.info('Then authenticate: firebase login');
    logger.info('You can run "npm run firebase:setup" in your project later');
    return;
  }

  logger.success('✓ Firebase CLI detected');

  // Check if authenticated
  const isAuth = await isFirebaseAuthenticated();
  if (!isAuth) {
    logger.warning('Not authenticated with Firebase');
    logger.info('Run: firebase login');
    logger.info('You can run "npm run firebase:setup" in your project later');
    return;
  }

  logger.success('✓ Firebase authenticated');

  // Get current project
  const projectId = await getCurrentFirebaseProject();
  if (!projectId) {
    logger.warning('No Firebase project selected');
    logger.info('Select a project with: firebase use <project-id>');
    logger.info('Or create one with: firebase init');
    logger.info('You can run "npm run firebase:setup" in your project later');
    return;
  }

  logger.success(`✓ Using Firebase project: ${projectId}`);

  // Get Firebase config
  logger.info('Fetching Firebase configuration...');
  const config = await getFirebaseConfig(projectId);
  if (!config) {
    logger.info('You can run "npm run firebase:setup" in your project later');
    return;
  }

  // Create .env.local
  const success = await createEnvFile(projectDir, config);
  if (success) {
    logger.success('✓ Created .env.local with Firebase credentials');
    logger.info('');
    logger.info('⚠️  Next steps:');
    logger.info(`   1. Enable Authentication providers in Firebase Console:`);
    logger.info(
      `      https://console.firebase.google.com/project/${projectId}/authentication/providers`
    );
    logger.info('   2. Enable Google Sign-In and Email Link authentication');
  } else {
    logger.info('You can run "npm run firebase:setup" in your project later');
  }
}
