#!/usr/bin/env node

/**
 * Firebase Auto-Configuration Script
 *
 * This script uses the Firebase CLI to automatically configure your project
 * by fetching the Firebase config and writing it to .env.local
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ENV_FILE = path.join(process.cwd(), '.env.local');
const ENV_EXAMPLE = path.join(process.cwd(), '.env.example');

console.log('🔥 Firebase Auto-Configuration Script\n');

// Check if Firebase CLI is installed
function checkFirebaseCLI() {
  try {
    execSync('firebase --version', { stdio: 'ignore' });
    return true;
  } catch (error) {
    console.error('❌ Firebase CLI not found!\n');
    console.log('Please install it first:');
    console.log('  npm install -g firebase-tools\n');
    console.log('Then authenticate:');
    console.log('  firebase login\n');
    return false;
  }
}

// Check if user is logged in
function checkAuth() {
  try {
    execSync('firebase projects:list', { stdio: 'ignore' });
    return true;
  } catch (error) {
    console.error('❌ Not authenticated with Firebase!\n');
    console.log('Please run:');
    console.log('  firebase login\n');
    return false;
  }
}

// Get current Firebase project
function getCurrentProject() {
  try {
    const output = execSync('firebase use', { encoding: 'utf-8' });
    const match = output.match(/Active Project:\s+(\S+)/);
    return match ? match[1] : null;
  } catch (error) {
    return null;
  }
}

// Get Firebase web app config
function getFirebaseConfig(projectId) {
  try {
    console.log(`📱 Fetching Firebase config for project: ${projectId}...`);
    
    // Get web apps list
    const appsOutput = execSync(
      `firebase apps:list WEB --project ${projectId}`,
      { encoding: 'utf-8' }
    );
    
    // Parse app ID from output
    const appMatch = appsOutput.match(/│\s+(\S+)\s+│/);
    if (!appMatch) {
      console.error('❌ No web app found in Firebase project!');
      console.log('\nCreate a web app first:');
      console.log(`  firebase apps:create WEB --project ${projectId}`);
      return null;
    }
    
    const appId = appMatch[1];
    console.log(`✓ Found web app: ${appId}`);
    
    // Get app config
    const configOutput = execSync(
      `firebase apps:sdkconfig WEB ${appId} --project ${projectId}`,
      { encoding: 'utf-8' }
    );
    
    // Parse Firebase config from output
    const configMatch = configOutput.match(/const firebaseConfig = ({[\s\S]*?});/);
    if (!configMatch) {
      console.error('❌ Could not parse Firebase config!');
      return null;
    }
    
    // Extract config values
    const configStr = configMatch[1];
    const config = {};
    
    const parseValue = (key) => {
      const regex = new RegExp(`${key}:\\s*["']([^"']+)["']`);
      const match = configStr.match(regex);
      return match ? match[1] : '';
    };
    
    config.apiKey = parseValue('apiKey');
    config.authDomain = parseValue('authDomain');
    config.projectId = parseValue('projectId');
    config.storageBucket = parseValue('storageBucket');
    config.messagingSenderId = parseValue('messagingSenderId');
    config.appId = parseValue('appId');
    config.measurementId = parseValue('measurementId') || '';
    
    return config;
  } catch (error) {
    console.error('❌ Failed to fetch Firebase config:', error.message);
    return null;
  }
}

// Create .env.local file
function createEnvFile(config) {
  const envContent = `# Firebase Configuration
# Generated by firebase-setup script
# DO NOT commit this file to version control!

NEXT_PUBLIC_FIREBASE_API_KEY=${config.apiKey}
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${config.authDomain}
NEXT_PUBLIC_FIREBASE_PROJECT_ID=${config.projectId}
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${config.storageBucket}
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${config.messagingSenderId}
NEXT_PUBLIC_FIREBASE_APP_ID=${config.appId}
${config.measurementId ? `NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${config.measurementId}` : ''}
`;

  try {
    // Backup existing .env.local if it exists
    if (fs.existsSync(ENV_FILE)) {
      const backup = `${ENV_FILE}.backup.${Date.now()}`;
      fs.copyFileSync(ENV_FILE, backup);
      console.log(`📋 Backed up existing .env.local to: ${path.basename(backup)}`);
    }
    
    fs.writeFileSync(ENV_FILE, envContent.trim() + '\n');
    console.log('✓ Created .env.local');
    return true;
  } catch (error) {
    console.error('❌ Failed to create .env.local:', error.message);
    return false;
  }
}

// Main execution
async function main() {
  // Check prerequisites
  if (!checkFirebaseCLI() || !checkAuth()) {
    process.exit(1);
  }
  
  // Get current project
  const projectId = getCurrentProject();
  if (!projectId) {
    console.error('❌ No Firebase project selected!\n');
    console.log('Select a project first:');
    console.log('  firebase use <project-id>\n');
    console.log('Or create a new project:');
    console.log('  firebase init');
    process.exit(1);
  }
  
  // Get Firebase config
  const config = getFirebaseConfig(projectId);
  if (!config) {
    process.exit(1);
  }
  
  // Create .env.local
  if (!createEnvFile(config)) {
    process.exit(1);
  }
  
  console.log('\n✅ Firebase configuration complete!');
  console.log('\nNext steps:');
  console.log('  1. Run: npm run dev');
  console.log('  2. Open: http://localhost:3000');
  console.log('\n⚠️  Remember to enable Authentication providers in Firebase Console:');
  console.log(`     https://console.firebase.google.com/project/${projectId}/authentication/providers`);
}

main().catch((error) => {
  console.error('❌ Unexpected error:', error);
  process.exit(1);
});

